repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-yaml
    files: ^server/
  - id: end-of-file-fixer
    files: ^server/
  - id: trailing-whitespace
    files: ^server/

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    files: ^server/

- repo: https://github.com/pycqa/flake8
  rev: 7.1.1
  hooks:
  - id: flake8
    files: ^server/
    args: ["--config=server/setup.cfg"]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.1
  hooks:
  - id: mypy
    files: ^server/
    args: ["--config-file=server/setup.cfg"]
    additional_dependencies:
      [
        numpy==2.0.1,
        pandas-stubs==2.2.2.240807,
        types-pytz==2024.1.0.20240417,
        types-pytz==2024.1.0.20240417,
        types-requests==2.32.0.20240712,
        types-tqdm==4.66.0.20240417,
      ]
