# coding: utf-8
from sqlalchemy import Column, Float, Integer, MetaData, Table, Text

metadata = MetaData()


t_collision = Table(
    'collision', metadata,
    Column('OBJECTID', Integer),
    Column('SE_ANNO_CAD_DATA', Text),
    Column('INCKEY', Integer),
    Column('COLDETKEY', Integer),
    Column('REPORTNO', Text),
    Column('STATUS', Text),
    Column('ADDRTYPE', Text),
    Column('INTKEY', Float),
    Column('LOCATION', Text),
    Column('EXCEPTRSNCODE', Text),
    Column('EXCEPTRSNDESC', Text),
    Column('SEVERITYCODE', Text),
    Column('SEVERITYDESC', Text),
    Column('COLLISIONTYPE', Text),
    Column('PERSONCOUNT', Integer),
    Column('PEDCOUNT', Integer),
    Column('PEDCYLCOUNT', Integer),
    Column('VEHCOUNT', Integer),
    Column('INJURIES', Integer),
    Column('SERIOUSINJURIES', Integer),
    Column('FATALITIES', Integer),
    Column('INCDATE', Text),
    Column('INCDTTM', Text),
    Column('JUNCTIONTYPE', Text),
    Column('SDOT_COLCODE', Float),
    Column('SDOT_COLDESC', Text),
    Column('INATTENTIONIND', Text),
    Column('UNDERINFL', Text),
    Column('WEATHER', Text),
    Column('ROADCOND', Text),
    Column('LIGHTCOND', Text),
    Column('DIAGRAMLINK', Text),
    Column('REPORTLINK', Text),
    Column('PEDROWNOTGRNT', Text),
    Column('SDOTCOLNUM', Float),
    Column('SPEEDING', Text),
    Column('STCOLCODE', Float),
    Column('ST_COLDESC', Text),
    Column('SEGLANEKEY', Integer),
    Column('CROSSWALKKEY', Integer),
    Column('HITPARKEDCAR', Text),
    Column('SPDCASENO', Text),
    Column('Source of the collision report', Text),
    Column('Source description', Text),
    Column('Added by User', Text),
    Column('Added date', Text),
    Column('Modified by', Text),
    Column('Modified date', Text),
    Column('x', Float),
    Column('y', Float)
)


t_person = Table(
    'person', metadata,
    Column('OBJECTID', Integer),
    Column('COLLISIONPSNDETKEY', Integer),
    Column('COLDETKEY', Integer),
    Column('Added date', Text),
    Column('ST_AGE', Float),
    Column('ST_ARBG_STAT', Float),
    Column('ST_ARBG_STAT_DESC', Text),
    Column('ST_ALCHL_TST_RSLTS', Float),
    Column('ST_ALCHL_TST_RSLTS_DESC', Float),
    Column('ST_CITED', Text),
    Column('ST_CLTHNG_VSBLTY', Float),
    Column('ST_CLTHNG_VSBLTY_DESC', Text),
    Column('ST_CONTRBCIR_CD1', Float),
    Column('ST_CONTRBCIR1_DESC', Text),
    Column('ST_CONTRBCIR_CD2', Float),
    Column('ST_CONTRBCIR2_DESC', Text),
    Column('ST_CONTRBCIR_CD3', Float),
    Column('ST_CONTRBCIR3_DESC', Text),
    Column('ST_DIR_FM', Float),
    Column('ST_DIR_FM_DESC', Text),
    Column('ST_DIR_TO', Float),
    Column('ST_DIR_TO_DESC', Text),
    Column('ST_DRE1', Float),
    Column('ST_DRE1_DESC', Text),
    Column('ST_DRE2', Float),
    Column('ST_DRE2_DESC', Text),
    Column('ST_DRIVER_MISC_ACT_CD1', Text),
    Column('ST_DRIVER_MISC_ACT1_DESC', Text),
    Column('ST_DRIVER_MISC_ACT_CD2', Text),
    Column('ST_DRIVER_MISC_ACT2_DESC', Text),
    Column('ST_DRVR_ACTNS3', Text),
    Column('ST_DRVR_ACTNS3_DESC', Text),
    Column('ST_EJCTN', Float),
    Column('ST_EJCTN_DESC', Text),
    Column('ST_GENDER', Text),
    Column('ST_GENDER_DESC', Text),
    Column('ST_HZMT_IND', Float),
    Column('ST_HZMT_IND_DESC', Text),
    Column('ST_HELMET', Float),
    Column('ST_HELMET_DESC', Text),
    Column('ST_INJRY_CLSS', Float),
    Column('ST_INJRY_CLSS_DESC', Text),
    Column('ST_PARTCPNT_TYPE', Integer),
    Column('ST_PARTCPNT_TYPE_DESC', Text),
    Column('ST_PED_ACT_CD', Float),
    Column('ST_PED_ACT_DESC', Text),
    Column('ST_PED_TYPE', Float),
    Column('ST_PED_TYPE_DESC', Text),
    Column('ST_PED_WAS_USING_CD', Float),
    Column('ST_PED_WAS_USING_DESC', Text),
    Column('ST_RESTRAINT', Float),
    Column('ST_RESTRAINT_DESC', Text),
    Column('ST_SOBRIETY_CD', Float),
    Column('ST_SOBRIETY_DESC', Text),
    Column('ST_ST_PSTON', Float),
    Column('ST_ST_PSTON_DESC', Text),
    Column('ST_UNIT', Integer),
    Column('SE_ANNO_CAD_DATA', Text),
    Column('Source of the collision report', Text),
    Column('Source description', Text),
    Column('Incident Date', Text),
    Column('Incident Date Time', Text),
    Column('Report Number', Text),
    Column('Added by User', Text),
    Column('Modified by', Float),
    Column('Modified date', Float),
    Column('x', Float),
    Column('y', Float)
)
